# Generated by Django 2.1.5 on 2019-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGitHub', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('pushed_at', models.DateField()),
            ],
        ),
    ]
