# Generated by Django 2.1.5 on 2019-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitHub', '0002_auto_20190121_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='pushed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
