# Generated by Django 2.1.5 on 2019-01-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitHub', '0003_auto_20190121_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
