# Generated by Django 2.1.5 on 2019-01-24 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitHub', '0004_auto_20190124_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='sync_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
